using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SplitOrStealBot
{
    public enum Characters
    {
        Sysadmin = 5,
        Eminemnt = 6,
        OldTimette = 7,
        OldTimer = 8,
        GameDeveloper = 9,
        Barista = 10,
        Paramedic = 11,
        DresdenDoll = 12,
        RootRadical = 13,
        BuildeyBoye = 14,
        ArtsGraduateF = 15,
        TouristF = 16,
        TouristM = 17,
        DestroyerOfWorlds = 18,
        PartyVanDriverF = 19,
        PartyVanDriverM = 20,
        Unreleased21 = 21,
        Unreleased22 = 22,
        Unreleased23 = 23,
        Unreleased24 = 24,
        Unreleased25 = 25,
        Unreleased26 = 26,
        LiveStreamDistruptor = 27,
        Spectre = 28,
        Spectress = 29,
        JeanneDsplit = 30,
        ThiefHunter = 31,
        TubeCommenterM = 32,
        TubeCommenterF = 33,
        MrSkeltal = 34,
        IdleMancer = 35,
        BeastMaster = 36,
        Vixen = 37,
        Linkle = 38,
        PrairieMaiden = 39,
        PizzaPrincess = 40,
        RedWitch = 41,
        Bard = 42,
        BurgerMeister = 43,
        Brigand = 44,
        Rogue = 45,
        Ailurus = 46,
        RedWizard = 47,
        Nephthys = 48,
        Anubis = 49,
        NeutralColossus = 50,
        TubeLord = 51,
        Torbmh = 52,
        GentleGiant = 53,
        ThievingBeast = 54,
        FdaOfficial = 55,
        FriendlyButcher = 56,
        Diabolus = 57,
        TheSainted = 58,
        GodOfLostTime = 65,
    }
}
